<script setup lang="ts">
import { onMounted, ref } from 'vue'
import { RouterLink, useRoute } from 'vue-router'

import { useAuth } from '@/composables/useAuth'
import { useLocale } from '@/composables/useLocale'
import { pagePaths } from '@/data/locales'
import { getDownloadLink } from '@/services/apiService'
import { forgetSession } from '@/services/authService'
import {
  AccountError,
  NotSignedInError,
  createFolder,
  deleteAccount,
  deleteFolder,
  getProfile,
  listBlocks,
  listFolders,
  removeVideo,
  renameFolder,
  setNickname,
  unblockUser,
  type Folder,
  type SavedVideo,
} from '@/services/accountService'

const route = useRoute()
const { user, loginAvailable, ready, refresh } = useAuth()
const { copy, localize } = useLocale()

const folders = ref<Folder[]>([])
const blocks = ref<string[]>([])
const loading = ref(false)
const busy = ref(false)
const error = ref('')

const newFolderName = ref('')
const renamingId = ref('')
const renameValue = ref('')
const confirmingDelete = ref(false)
const deleting = ref(false)
const deleted = ref(false)

const nickname = ref('')
const nicknameDraft = ref('')
const nicknameNotice = ref('')
const savingNickname = ref(false)

onMounted(async () => {
  await refresh()

  if (user.value) await load()
})

async function load(): Promise<void> {
  loading.value = true
  error.value = ''

  try {
    folders.value = await listFolders()
    blocks.value = await listBlocks()

    // The nickname is generated by the API the first time it is asked for,
    // so this is also what creates it for a brand new account.
    const profile = await getProfile()
    nickname.value = profile.nickname
    nicknameDraft.value = profile.nickname
  } catch (failure) {
    handle(failure)
  } finally {
    loading.value = false
  }
}

async function saveNickname(): Promise<void> {
  const wanted = nicknameDraft.value.trim()
  if (!wanted || savingNickname.value || wanted === nickname.value) return

  savingNickname.value = true
  nicknameNotice.value = ''

  try {
    await setNickname(wanted)
    // The API trims and re-checks the value, so ask it what it stored rather
    // than assuming the text that was typed.
    const profile = await getProfile()
    nickname.value = profile.nickname
    nicknameDraft.value = profile.nickname
    nicknameNotice.value = copy.value.library.nicknameSaved
  } catch (failure) {
    handle(failure)
  } finally {
    savingNickname.value = false
  }
}

/** Turns a service failure into something the page can show. */
function handle(failure: unknown): void {
  if (failure instanceof NotSignedInError) {
    user.value = null
    error.value = copy.value.library.sessionEnded
    return
  }

  if (failure instanceof AccountError && failure.message) {
    error.value = failure.message
    return
  }

  error.value = copy.value.library.genericError
}

async function addFolder(): Promise<void> {
  const name = newFolderName.value.trim()
  if (!name || busy.value) return

  busy.value = true
  error.value = ''

  try {
    folders.value = [...folders.value, await createFolder(name)]
    newFolderName.value = ''
  } catch (failure) {
    handle(failure)
  } finally {
    busy.value = false
  }
}

function startRename(folder: Folder): void {
  renamingId.value = folder.id
  renameValue.value = folder.name
}

async function confirmRename(folder: Folder): Promise<void> {
  const name = renameValue.value.trim()
  if (!name) return

  try {
    await renameFolder(folder.id, name)
    folder.name = name
    renamingId.value = ''
  } catch (failure) {
    handle(failure)
  }
}

async function removeFolder(folder: Folder): Promise<void> {
  const question = copy.value.library.confirmDeleteFolder.replace('{name}', folder.name)
  if (!window.confirm(question)) return

  try {
    await deleteFolder(folder.id)
    folders.value = folders.value.filter((entry) => entry.id !== folder.id)
  } catch (failure) {
    handle(failure)
  }
}

async function removeSaved(folder: Folder, video: SavedVideo): Promise<void> {
  try {
    await removeVideo(folder.id, video.video_id)
    folder.videos = folder.videos.filter((entry) => entry.video_id !== video.video_id)
  } catch (failure) {
    handle(failure)
  }
}

async function unblock(userId: string): Promise<void> {
  try {
    await unblockUser(userId)
    blocks.value = blocks.value.filter((entry) => entry !== userId)
  } catch (failure) {
    handle(failure)
  }
}

async function removeAccount(): Promise<void> {
  deleting.value = true
  error.value = ''

  try {
    await deleteAccount()

    // The session belongs to an account that no longer exists, so it is not
    // just misleading to keep, it is useless.
    forgetSession()
    user.value = null
    deleted.value = true
  } catch (failure) {
    handle(failure)
  } finally {
    deleting.value = false
  }
}

function videoTitle(video: SavedVideo): string {
  const description = video.description?.trim()

  return description ? description : copy.value.library.videoFallback
}

function savedCount(folder: Folder): string {
  return copy.value.library.savedCount.replace('{count}', String(folder.videos.length))
}

function videoPage(video: SavedVideo): string {
  return getDownloadLink(video.video_id)
}
</script>

<template>
  <div class="container py-5">
    <h1 class="mb-4">{{ copy.library.heading }}</h1>

    <div v-if="error" class="alert alert-danger" role="alert">{{ error }}</div>

    <div v-if="deleted" class="alert alert-success" role="alert">
      <h2 class="h5">{{ copy.library.deletedTitle }}</h2>
      <p class="mb-0">{{ copy.library.deletedBody }}</p>
    </div>

    <div v-else-if="!user" class="row">
      <div class="col-lg-7">
        <p class="lead">{{ copy.library.signInLead }}</p>
        <p v-if="ready && !loginAvailable" class="text-muted">
          {{ copy.common.signInUnavailable.before
          }}<RouterLink :to="localize(pagePaths.home)">{{ copy.common.signInUnavailable.link }}</RouterLink
          >{{ copy.common.signInUnavailable.after }}
        </p>
        <RouterLink
          v-else
          class="btn btn-primary"
          :to="{ path: localize(pagePaths.login), query: { return: route.path } }"
        >
          {{ copy.nav.signIn }}
        </RouterLink>
      </div>
    </div>

    <div v-else>
      <p v-if="loading" class="text-muted">{{ copy.library.loading }}</p>

      <form class="row g-2 mb-4" @submit.prevent="addFolder">
        <div class="col-sm-6">
          <label class="visually-hidden" for="new-folder">{{ copy.library.newFolderName }}</label>
          <input
            id="new-folder"
            v-model="newFolderName"
            class="form-control"
            type="text"
            maxlength="60"
            :placeholder="copy.library.newFolderName"
          />
        </div>
        <div class="col-auto">
          <button class="btn btn-outline-primary" type="submit" :disabled="busy || !newFolderName.trim()">
            {{ copy.library.createFolder }}
          </button>
        </div>
      </form>

      <p v-if="!loading && folders.length === 0" class="text-muted">
        {{ copy.library.emptyFoldersBefore }}<strong>{{ copy.library.emptyFoldersStrong }}</strong
        >{{ copy.library.emptyFoldersAfter }}
      </p>

      <section v-for="folder in folders" :key="folder.id" class="card mb-4">
        <div class="card-body">
          <div class="d-flex flex-wrap align-items-center gap-2 mb-3">
            <template v-if="renamingId === folder.id">
              <input
                v-model="renameValue"
                class="form-control form-control-sm w-auto"
                type="text"
                maxlength="60"
                @keyup.enter="confirmRename(folder)"
              />
              <button class="btn btn-sm btn-primary" type="button" @click="confirmRename(folder)">
                {{ copy.library.save }}
              </button>
              <button class="btn btn-sm btn-link" type="button" @click="renamingId = ''">
                {{ copy.library.cancel }}
              </button>
            </template>
            <template v-else>
              <h2 class="h5 mb-0">{{ folder.name }}</h2>
              <span class="text-muted small">{{ savedCount(folder) }}</span>
              <button class="btn btn-sm btn-link ms-auto" type="button" @click="startRename(folder)">
                {{ copy.library.rename }}
              </button>
              <button class="btn btn-sm btn-link text-danger" type="button" @click="removeFolder(folder)">
                {{ copy.library.delete }}
              </button>
            </template>
          </div>

          <p v-if="folder.videos.length === 0" class="text-muted mb-0">{{ copy.library.nothingSaved }}</p>

          <div v-else class="row row-cols-1 row-cols-sm-2 row-cols-lg-3 g-3">
            <div v-for="video in folder.videos" :key="video.video_id" class="col">
              <div class="card h-100">
                <img
                  v-if="video.thumbnail_url"
                  :src="video.thumbnail_url"
                  class="card-img-top"
                  style="height: 120px; object-fit: cover"
                  loading="lazy"
                  alt=""
                />
                <div class="card-body d-flex flex-column">
                  <p class="card-text small flex-grow-1">{{ videoTitle(video) }}</p>
                  <div class="d-flex gap-2">
                    <a class="btn btn-sm btn-primary" :href="videoPage(video)">{{ copy.library.open }}</a>
                    <button class="btn btn-sm btn-outline-danger" type="button" @click="removeSaved(folder, video)">
                      {{ copy.library.remove }}
                    </button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </section>

      <section class="card mb-4">
        <div class="card-body">
          <h2 class="h5">{{ copy.library.nicknameHeading }}</h2>
          <p class="text-muted small mb-3">{{ copy.library.nicknameHelp }}</p>

          <form class="row g-2" @submit.prevent="saveNickname">
            <div class="col-sm-6">
              <label class="visually-hidden" for="nickname">{{ copy.library.nicknameLabel }}</label>
              <input
                id="nickname"
                v-model="nicknameDraft"
                class="form-control"
                type="text"
                maxlength="20"
                :placeholder="copy.library.nicknamePlaceholder"
              />
            </div>
            <div class="col-auto">
              <button
                class="btn btn-outline-primary"
                type="submit"
                :disabled="savingNickname || !nicknameDraft.trim() || nicknameDraft.trim() === nickname"
              >
                {{ copy.library.saveNickname }}
              </button>
            </div>
          </form>

          <p v-if="nicknameNotice" class="text-success small mt-2 mb-0">{{ nicknameNotice }}</p>
        </div>
      </section>

      <section v-if="blocks.length > 0">
        <h2 class="h5">{{ copy.library.blocksHeading }}</h2>
        <p class="text-muted small">{{ copy.library.blocksHelp }}</p>
        <ul class="list-inline">
          <li v-for="blocked in blocks" :key="blocked" class="list-inline-item">
            <span class="badge text-bg-secondary">{{ blocked }}</span>
            <button class="btn btn-sm btn-link" type="button" @click="unblock(blocked)">
              {{ copy.library.unblock }}
            </button>
          </li>
        </ul>
      </section>

      <section class="border border-danger rounded p-3 mt-5">
        <h2 class="h5 text-danger">{{ copy.library.deleteAccountHeading }}</h2>
        <p>{{ copy.library.deleteAccountBody }}</p>

        <div v-if="!confirmingDelete">
          <button class="btn btn-outline-danger" type="button" @click="confirmingDelete = true">
            {{ copy.library.deleteAccountButton }}
          </button>
        </div>

        <div v-else class="d-flex flex-wrap align-items-center gap-2">
          <span class="fw-semibold">{{ copy.library.deleteAccountConfirm }}</span>
          <button class="btn btn-danger" type="button" :disabled="deleting" @click="removeAccount">
            {{ deleting ? copy.library.deleting : copy.library.deleteAccountYes }}
          </button>
          <button class="btn btn-link" type="button" :disabled="deleting" @click="confirmingDelete = false">
            {{ copy.library.cancel }}
          </button>
        </div>
      </section>
    </div>
  </div>
</template>
